Zangband 2.7.5pre1

diff --git a/makefile.in b/makefile.in
--- a/makefile.in
+++ b/makefile.in
@@ -102,6 +102,8 @@ endif
 ##
 ## Compile zangband.
 ##
+default: zangband .makefiles
+
 zangband: $(objs-y)
 	$(LINK) $(CFLAGS) -o $@ $^ $(LDFLAGS) $(LIBS) $(DEFS)
 
@@ -185,7 +187,11 @@ distgz: dist
 	gzip -9 zangband-$(VERSION).tar
 	-rm -rf $(DESTDIR)
 
-clean:
+# Minor cleaning
+dust:
+	-rm -f $(dust-files)
+	
+clean: dust
 	-rm -f $(clean-files)
 
 distclean: clean
@@ -226,6 +232,21 @@ configure.in: .version
 	cat configure.in | sed -e "s/AC_INIT.*$$/AC_INIT\(Zangband,\ `cat .version`,\ bugs@zangband.org\)/" > configure.new
 	mv configure.new configure.in
 		
+# Test to see that all source files are in the other makefiles.
+.makefiles: $(makefiles)
+	for i in $(notdir $(NORMOBJS)) ; do \
+		for j in $(makefiles) ; do \
+			if [ x"`grep $$i $$j | sed 1q`" == x ]; then \
+				echo "Error: makefile $$j has $$i missing"; \
+				k="stop"; \
+			fi; \
+		done; \
+	done; \
+	if [ "x$$k" == "xstop" ]; then \
+		exit 1; \
+	fi; \
+	touch .makefiles;
+
 
 .PHONY: dirs base installbase install uninstall dist distcheck distgz \
-		 clean distclean test
+		 dust clean distclean test
